const coursesTypes = {
	GET_ALL_COURSES_START: 'GET_ALL_COURSES_START',
	GET_ALL_COURSES_SUCCESS: 'GET_ALL_COURSES_SUCCESS',
	GET_ALL_COURSES_FAIL: 'GET_ALL_COURSES_FAIL',

	GET_ONE_COURSES_START: "GET_ONE_COURSES_START",
	GET_ONE_COURSES_SUCCESS: "GET_ONE_COURSES_SUCCESS",
	GET_ONE_COURSES_FAIL: "GET_ONE_COURSES_FAIL",

	GET_COURSES_BY_ID_START: "GET_COURSES_BY_ID_START",
	GET_COURSES_BY_ID_SUCCESS: "GET_COURSES_BY_ID_SUCCESS",
	GET_COURSES_BY_ID_FAIL: "GET_COURSES_BY_ID_FAIL",

	POST_COURSES_START: "POST_COURSES_START",
	POST_COURSES_SUCCESS: "POST_COURSES_SUCCESS",
	POST_COURSES_FAIL: "POST_COURSES_FAIL",

	EDIT_COURSES_START: "EDIT_COURSES_START",
	EDIT_COURSES_SUCCESS: "EDIT_COURSES_SUCCESS",
	EDIT_COURSES_FAIL: "EDIT_COURSES_FAIL",

	ADD_CHAPTERS_START: "ADD_CHAPTERS_START",
	ADD_CHAPTERS_SUCCESS: "ADD_CHAPTERS_SUCCESS",
	ADD_CHAPTERS_FAIL: "ADD_CHAPTERS_FAIL",
};

export default coursesTypes;